version: '3'
services:
    server:
      build: ./
      image: test-udp-server
      command: node server.js
      ports: 
        - '3000:3000'
              
    client:
      build: ./
      image: test-udp-client
      command: node client.js